import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header/Header";
import Galaxy from "@/components/Galaxy/Galaxy";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Header />
        <Galaxy />
        <main className='container h-dvh z-10 flex flex-col justify-center align-middle px-5 py-5 border backdrop-blur-sm'>{children}</main>
      </body>
    </html>
  );
}
